### ISSUE TITLE
COH2 Stats App - README

### ISSUE THREAD

**Issue by petrvecera** [petrvecera/coh2ladders#126]
Let's create a README describing the app. 
I would describe it here https://github.com/petrvecera/coh2ladders/tree/master/packages/app

You can add screenshots and other things the same way it's here 
https://github.com/petrvecera/coh2ladders/pull/125

FYI Tip: it's best to write the readme using github online editor - so you can easily put images there

**Comment by JohannesMerkt** [comment]
Just now I was investigating the issue you ran into when building the app. I decided to remove the electron-active-window package since it causes alot of problems and provides very little value (it was used to check if the game is currently in active use to not notify when the user is in game). This should then allow you to build the app.  Then I will write a readme. 

Maybe I can also try out how to use a github action to build the app

**Comment by JohannesMerkt** [comment]
@petrvecera also i noticed when you clone the repo and look at the changed files in git it shows me that the appIcon.ico file was changed. When I try to open it it is broken. 

Does that happen to you too? 

I commited a working ico file before and when I clone the repo it is broken again. not sure why this happens, but if it happens the app will not be able to run and crashes, since it cannot load the broken ico file.

**Comment by petrvecera** [comment]
I've created a several tickets - you can pick anything you like
@JohannesMerkt https://github.com/petrvecera/coh2ladders/issues?q=is%3Aissue+is%3Aopen+label%3Adesktop-app

Yes something is wrong with the icon - it always show as changed. It could be prettier it could be messing it up / or git. I added it to gitattributes
![image](https://user-images.githubusercontent.com/8086995/151670672-6726b219-f30c-4e66-9d08-5cc123a60bab.png)


Please try to commit a working version. It could be also prettier who tries to change it.
