### ISSUE TITLE
my playercard is bugged 

### ISSUE THREAD

**Issue by micronanomilo** [petrvecera/coh2ladders#173]
So I searched my name on this around 5 months ago, it works just fine. 

I came back to check again just yesterday, I am able to see my name, however, after I clicked on the result; the screen becomes blank (nothing but a white page) 
I tried a simple diagnoses such as clearing web cookies, changing browser/device/ internet. Still, it doesn't work so I am here to seek help

**Comment by micronanomilo** [comment]
Also, this is a link to my player card 
https://coh2stats.com/players/76561198858149194

**Comment by petrvecera** [comment]
Thank you for the report. This is an issue on our side - the Relic servers are returning us something we don't expect - we will investigate and fix this.

**Comment by petrvecera** [comment]
Hi the issue has been fixed.  It's deployed on the dev version https://coh2-ladders-dev.web.app/players/76561198858149194  << you can use this web in meantime. It's gonna be on coh2stats.com with next bigger update. 


The issue is this - relic lost info about this player team / maybe it was deleted user? idk 
![image](https://user-images.githubusercontent.com/8086995/155815399-0b4fc216-203a-4b52-b0f3-3633f980122a.png)
